### ISSUE TITLE
Add tests to Project and Partnership e2e

### ISSUE THREAD

**Issue by zkhin** [SeedCompany/cord-api-v3#1032]

**Comment by reneepe** [comment]
Project's MOU start/end dates are returned when they exist.

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/d44aebc2-3c60-45ca-b8c4-70f0db863d3a)

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/1b4e7dfe-b305-467f-b164-b32edb6cd847)

Otherwise, partnerships are created without mou dates.

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/f20c7fe6-a520-4f04-8309-b6cfab39c08f)

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/aeb788f1-bfdd-4483-9c09-cfe781a09862)

**Comment by reneepe** [comment]
@zkhin Is funding type supposed to be applied only to a managing partner? I tried applying it to a funding partner. Here's the error message: 

![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/d446f328-2291-4aa4-9836-f1dac22f314e)

**Comment by zkhin** [comment]
The `fundingType` can only have a value when the `types` contains `Managing` type.

**Comment by CarsonF** [comment]
@reneepe I know, very unintuitive right 😞
