### ISSUE TITLE
Create Budget function

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#119]
WF version: https://seedcompany.my.workfront.com/task/view?ID=5e41c8a6015705e36d4c1d17e566c36f

Create operation in the Budget service.

**Comment by candleshine** [comment]
Create for budgets is pretty involved and specialized in its workflow.  
1) a pending budget when it is initialized needs to prepopulate a bunch of records inside (currently represented by an array of BudgetDetails, but this should change) . The records are for each year betweeen MOU start year and MOU end Year and for each financial partner (think a 2x2 array, right?)  But instead of an array these are each a graph-relationship to what we should now call a _Record_ or BudgetRecord (formerly BudgetDetail).  There is a need to pass in the project ID as well because the Budget is on a project, and that relationship needs to be added.  0
2) Once these are initialized, they can only have their amounts updated.  And probably from the Project mutation not the Budget mutation.  Projects need to have multiple Budgets, because we will sometimes list the pending budgets, current budget (only one can be current) and superceded budgets, which is an archive of past current budgets.  
3) CUrrent Budgets cannot be changed when the project is Active.

Because these workflows are specialized and don't fit into a CRUD framework, I think we need to close this ticket @michaelmarshall

**Comment by michaelmarshall** [comment]
sounds good
