### ISSUE TITLE
Remove status from UpdateBudget

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#1205]
We don't want users to be able to change status directly. Only via status changes to project should this be updated.

**Comment by glassblowerscat** [comment]
> Only via status changes to project should this be updated.

Okay, so it seems like we can't remove the `status` field from `UpdateBudget` because the `update()` method of the Budget Service needs to be able to use this when called internally. So instead we need to modify the `budget` field of `UpdateBudgetInput` so that it excludes the `status` field from `UpdateBudget`. Is this accurate?

**Comment by CarsonF** [comment]
Sure we can just drop the `@Field` decorator to make it private.
