### ISSUE TITLE
[BUG] Can create duplicate Partners with same Organization

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1408]
I created a Partner with a newly created Organization. When searching for the Partner I was only able to find the Organization in the search results.

I created a Partner again with the same name and Organization.

Later in sorting the Partner List I found both of the Partners I created, with identical names and Organizations.

We should limit Partners to unique names.

**Comment by frankyma** [comment]
@sethmcknight I'm not too clear what the issue/approach is

> I created a Partner with a newly created Organization. When searching for the Partner I was only able to find the Organization in the search results.

This is a separate issue, will be fixed by https://github.com/SeedCompany/cord-field/issues/607
> I created a Partner again with the same name and Organization.

When creating partner (and searching for org on that searchbar), do we omit organizations that are already partners?  In otherwords, can there be only one partner per organization?

> Later in sorting the Partner List I found both of the Partners I created, with identical names and Organizations.
> We should limit Partners to unique names.

Partners don't have names, they show the names of their organizations.  If we enforce only 1 partner per organization their "names" will be unique
