### ISSUE TITLE
Delete child base node

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#1526]
We need to refactor how we delete child nodes. Get with me when you are ready to work this.

**Comment by frankyma** [comment]
Approach:

1. On create, each resource will have a canDelete property node (value = true but doesn't matter)
2. @michaelmarshall will create the permissions to this canDelete property
3. On the delete method for each service, check if user has a `canRead` permission for this canDelete property, if so, run the refactored delete query: https://github.com/SeedCompany/cord-api-v3/pull/1320
4. ^ expose this permission on the GQL schema (currently hardcoded)

**Comment by ParkeBrown** [comment]
@CarsonF is this one you'd pick up to review?

**Comment by CarsonF** [comment]
Mmm probably not. Not at least without talking to @michaelmarshall about it semi in depth.

**Comment by elisabeth-sorrell** [comment]
@michaelmarshall just checked against language and internship engagements, and is working as expected (or at least how I understand it to work). Did the following:
1. UI: create a language project and intern project
2. UI: create an engagement for both
3. API: using the engagement ID from both, use the deleteEngagement mutation
4. UI: refresh the page
5. UI: check the projects that had the engagements and they do not appear since they've been deleted.

**Comment by elisabeth-sorrell** [comment]
... also checked deleting a user and is working

**Comment by elisabeth-sorrell** [comment]
... delete project also working

**Comment by elisabeth-sorrell** [comment]
... delete language also working

**Comment by elisabeth-sorrell** [comment]
@michaelmarshall I can keep checking other nodes, but I'm pretty good with closing this and adding deletion for other stuff if needed as we go along, or fixing any bugs that come up, or whatever you think.
