### ISSUE TITLE
Getting "Could not set departmentId on Project" error when RegionalDirector approve Project, but It got approved on page reloading

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1528]
**Roles:** RegionalDirector , FinancialAnalyst , Controller , FieldOperationsDirector , Administrator , Intern , ProjectManager

**Describe the bug**
Getting `Could not set departmentId on Project` error when RegionalDirector approve Project, but It got approved on page reloading.

**Steps to Reproduce**

1. Login as admin user.
1. Create New Project and go to created Project's detail page.
1. Advance project step upto `PendingRegionalDirectorApproval`.
1. Login as `RegionalDirector` and go to Project detail page.
1. Click on `PendingRegionalDirectorApproval`.
1. Refresh Page.

**Expected Result**
RegionalDirector should be allowed to advance the project from `PendingRegionalDirectorApprovall` step without error.

**Actual Result**
Getting `Could not set departmentId on Project` error when RegionalDirector approve Project, but It got approved on page reloading.
See video - https://drive.google.com/file/d/1idAQuJt7CR_MBB-ApggrU9Uje_YiqaL3/view?usp=sharing

CordAPIV3# cab67ddd

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466757659) by [Unito](https://www.unito.io)

**Comment by elisabeth-sorrell** [comment]
The problem occurs because of the set-department-id handler when the project advances. If the project advances without a budget, the error is thrown. Talked to @CarsonF and he said it might be better to wait and treat this validation issue more holistically.

@CarsonF, I'm fine with going ahead and seeing if I can start on a first iteration of that, but we may need a conversation as far as the workflow for when the fundingAccount is created, budgets, etc because I'm not even sure whether the validation should happen before advancing the step, or some other time during the project's workflow.

@ParkeBrown going to put this back into Sprint Planning for now and unassigning myself.

**Comment by iPiyushPatel** [comment]
Hi @sethmcknight @elisabeth-sorrell @michaelmarshall 
I've verified on latest develop 03765d75  and still replicate the issue, Attaching the video for reference. Reopening the task. Thanks! 
See video : 

https://user-images.githubusercontent.com/5212585/113819038-5dd41200-9796-11eb-9b30-a99ee4d310e5.mp4

**Comment by CarsonF** [comment]
Should be fixed by #should be fixed by #1791
