### ISSUE TITLE
"FinancialAnalyst" is not allowed to advance the project from "Finance Endorsement" step.

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1534]
**Roles:** FinancialAnalyst

**Describe the bug**
`FinancialAnalyst` is not allowed to advance the project from `Finance Endorsement` step.

**Steps to Reproduce**
1. Login as `Administrator`
2. Create New Project and go to created Project's detail page
3. Click on `Early Conversation` > `Submit for Concept Approval`               
4. Navigate Back to Project detail page by clicking the button from redirected page.
6. Click on `Pending Concept Approval` >`Approve`
5. Click on `Prep For Consultant Endorsement` > `Submit for Consultant Endorsement`
6. Click on `Pending Consultant Endorsement`
7. Login as `FinancialAnalyst` and click on new created project
8. Click on `Prep For Financial Endorsement`

**Expected Result**
`FinancialAnalyst` should be allowed to advance the project from `Finance Endorsement` step.

**Actual Result**
`FinancialAnalyst` is not allowed to advance the project from `Finance Endorsement` step.
See video - https://www.awesomescreenshot.com/video/1665169?key=d1c0fac18d544c79cb885128c48548fc

CordAPIV3# 13948548

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel just verified that Financial Analyst can advance from "Pending Financial Endorsement" to "Finalizing Proposal" the financial analyst isn't allowed to advance from "Preparing for Financial Endorsement" to "Pending Financial Endorsement" but that's expected behavior according to https://github.com/SeedCompany/cord-api-v3/wiki/Project-Workflows

**Comment by elisabeth-sorrell** [comment]
@ParkeBrown putting into review for verification.

**Comment by iPiyushPatel** [comment]
Hi @elisabeth-sorrell @ParkeBrown 
I've tested on the latest develop a99ebf10 and observed that Financial Analyst could not advance from `Pending Financial Endorsement` to `Finalizing Project Proposal`.
As per [wiki](https://github.com/SeedCompany/cord-api-v3/wiki/Project-Workflows#step-6--pending-financial-endorsement), FA should be allowed to do so.
See video: https://drive.google.com/file/d/1W3FpW0WdFiOhvtdKV35Z9oYX_gJBTEQy/view?usp=drivesdk

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel I'll look into this... weird though because I had verified that an FA could go from Pending to Finalizing. I'll double check and make sure.
Note: 
1. if the FA **_isn't_** a member of the project, they cannot advance the step.
2. if the FA **_is_** a member of the project but **_does not_** have the FA role on that membership, they cannot advance the step.

**Comment by elisabeth-sorrell** [comment]
Yeah, just verified again that an FA member of the project with FA role can advance from Pending to Finalizing. Not sure what's going on here.......

**Comment by iPiyushPatel** [comment]
@elisabeth-sorrell @ParkeBrown 
I've verified on the latest develop a99ebf10 branch and it's working fine.

**Comment by elisabeth-sorrell** [comment]
Putting into Sprint Closed, then
