### ISSUE TITLE
Project created by other users are not displayed on the Project listing page for "consultant" user

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#1585]
**Roles:** Consultant

**Describe the bug**
Project created by other users are not displayed on the Project listing page for `consultant` user

**Steps to Reproduce**
1. Login as `Administrator` user
2. Create New Project and go to created Project's detail page
3. Login as `Consultant` user

**Expected Result**
Project created by other users should be displayed on the Project listing page for `consultant` user

**Actual Result**
Project created by other users are not displayed on the Project listing page for `consultant` user
See video - https://drive.google.com/file/d/1TvhxNCwANCt5-mMgMy1BCLObPFMSGuYB/view?usp=drivesdk

CordAPIV3# a99ebf10
Cord-field# 89ee57a1

**Comment by elisabeth-sorrell** [comment]
Note: blocking https://github.com/SeedCompany/cord-api-v3/issues/1533

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel I have no clue why, but this started to magically work again for me. It wasn't working Friday, and after coming in and starting up the UI/API/DB it's working again. Can you confirm?

**Comment by iPiyushPatel** [comment]
Hi @elisabeth-sorrell
I've verified again and I can still replicate the issue. But I see there is no new code pushed to the Develop branch after Fri. If you've made any changes, can you push/merge to Develop, please?

thanks

**Comment by elisabeth-sorrell** [comment]
Hi again, @iPiyushPatel
Thanks for taking a look again. I haven't made any changes to development, and I'm still puzzled about why it's working for me. Here's the steps I'm taking:

### Use Case 1:
1. Login as `admin/root` or some other user that can create projects, like `Project Manager`
2. create a project
3. Assign consultant as a project member with the `Consultant` role
4. Log out, Sign in as consultant
5. Project is listed

However, with the below steps it's _not_ working:
### Use Case 2:
1. Login as admin
2. create a project
3. log out, log in as consultant
4. project created is not listed.

In Use Case2, I can't see the listing, but isn't that expected behavior? Checking the [Schema Doc](https://docs.google.com/spreadsheets/d/e/2PACX-1vTe065oOA5S8QXqfBZQGqK193kIi4La2ex9ig-lDjeYmwekjMxyx-w-Mol8YRkI5YNp4o8PjI6bmaoM/pubhtml) it says that the consultant role has to be a member to see project's properties. 

So sorry to be stuck on this, but just want to make sure I'm following the correct steps to bring about the error.

**Comment by iPiyushPatel** [comment]
Hi @elisabeth-sorrell 
You have to follow steps from Use case 2 in order to bring the error.
I've tested on the latest develop 4dae6114 and the project is not showing for the `consultant` role, but it is showing for `Consultant Manager` role.
Let me know if you need any other info.

**Comment by elisabeth-sorrell** [comment]
Hi again, @iPiyushPatel 
okay, so looking at https://docs.google.com/spreadsheets/d/e/2PACX-1vTe065oOA5S8QXqfBZQGqK193kIi4La2ex9ig-lDjeYmwekjMxyx-w-Mol8YRkI5YNp4o8PjI6bmaoM/pubhtml, it says that the `Consultant Manager` role has global read on project properties, and the `Consultant` role has member read on Project properties. Which is why Use case 2 brings the error. A user with the `Consultant` role can only list projects that they are a member of. a user with `Consultant Manager` can list any project.

That's why I'm thinking that this is behaving as expected.......?  What are your thoughts?

**Comment by iPiyushPatel** [comment]
Well, I'm referring to the wiki at https://github.com/SeedCompany/cord-api-v3/wiki/Roles-&-Permissions#consultant and as per that, the Consultant should have access. 
@CarsonF @michaelmarshall what you think? There is confusion here, can you help?

**Comment by michaelmarshall** [comment]
@iPiyushPatel the perms for the consultant role are only for projects they are a member of
from the wiki:
![image](https://user-images.githubusercontent.com/1165460/103692208-13f04b80-4f5d-11eb-80e4-7c2572164d9f.png)
Should we change any wording to make it more clear I wonder? 
If a consultant can't see projects they aren't a member of then that is expected behavior. I'll wait for Piyush to be satisfied before closing this.

**Comment by elisabeth-sorrell** [comment]
@michaelmarshall and @iPiyushPatel just FYI that https://github.com/SeedCompany/cord-api-v3/issues/1533 is depending on this, too.

**Comment by iPiyushPatel** [comment]
Hi, @michaelmarshall @elisabeth-sorrell

Yes as per the wiki, Project is only displayed when the consultant user is a member of that project. the document is quite clear so I don't think we need to modify it. I have verified on the latest develop 080a4abd and I can still replicate the issue. For more clarification, I am adding a fresh video and other details of current behavior. Please find below. Thanks!

**Issue:**
The project is not displayed on the consultant user side even admin adds a consultant into the project as a member. For Consultant Manager, it works as expected.

**Step :**
1 .Login as root admin
2. Create a project and add 'Consultant', 'Consultant Manager' as a member
4. Login as `Consultant Manager` role 
5. Login as `Consultant` role 

See video: https://drive.google.com/file/d/1-8pr5QF5wmOoN-9KSesFmhYcSQ4tUfao/view?usp=drivesdk

Please advice.

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel hmmm. weird. Here's what I have:

https://user-images.githubusercontent.com/15220335/103806411-9ab72e00-501a-11eb-8615-d7ac8bdb784e.mov

the consultant user is able to list the project when they're assigned to it. Perhaps there's a discrepancy between our environments? maybe a restart with a fresh db is needed?

**Comment by iPiyushPatel** [comment]
Hi @elisabeth-sorrell

Wondering! Can you please confirm the behavior? I have verified on 080a4abd develop branch so can you please verify we are on the same branch or not? I can still replicate this issue. Also, I have tried creating a new consultant user but facing the same issue. Attaching the Video link for reference.

See Video: https://drive.google.com/file/d/1qz-NkMpeYOp5_18xyXNQZ1pdnuEJq3aC/view?usp=drivesdk

**Steps**
1. Clear database and Create a new user with a consultant role
2. Login as the root user and create a new Project
3. Assigned newly created consultant user to that project
4. Login as a newly created Consultant user

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel Hi! maybe we're working with two different versions of the db? or different sets of data?

Steps:
1. Perform `git pull` in the cord-field-api project
2. `docker-compose down`
3. `docker-compose pull db`
4. `docker-compose up -d db`
5. Wait for a minute or two, then restart the api, restart the UI, then try the steps above.

I just tried these steps, then your steps and was met with success..... still can't replicate the error :\

**Comment by iPiyushPatel** [comment]
Hi @elisabeth-sorrell @michaelmarshall

I have performed the above-mentioned steps and I can not replicate this issue. The project is displayed for the assigned consultant user. Thank you for the detailed clarification here and Sorry for the confusion. Thanks!

**Comment by elisabeth-sorrell** [comment]
@iPiyushPatel yay! I started having a feeling that it was environment related when we were having different results. 
I'll put this issue into Sprint closed.
@michaelmarshall @ParkeBrown just FYI
