### ISSUE TITLE
BudgetsInProgress API has not successfully pushed to DOMO since March 10th at 3pm

### ISSUE THREAD

**Issue by sethmcknight** [SeedCompany/cord-api-v3#1743]

**Comment by CarsonF** [comment]
It looks like that was because duplicate budget records were created during the March 8th-10th deadlock event.

During that deadlock the correct budget records were created, but the security permissions were waiting to apply. When users sent subsequent updates for projects they didn’t retrieve these new records (because they didn’t have permission yet). Thus our app code said another budget record needed to be created.

We want to change this logic (sync budget records handler) to not rely on user permissions, but it just hasn’t happened yet. We are also trying to get rid of the security code in the DB which would’ve prevented this too. Neither have gotten dev time yet.

We've removed the duplicate records that currently exist in the DB.

I’m updating the code now to do another check when creating a budget record to not create duplicates. This check ignores user permissions. #1748

Theoretically a duplicate could still be created if two updates were being done at the same time, but this is still a much smaller window.

**Comment by CarsonF** [comment]
Since the duplicates have been removed and data is pushing to DOMO again, I'm going to close this. The PR is a good check, but it only really matters if there's a deadlock kind of event again.
