### ISSUE TITLE
Budget Records Not Visible on Intern in "Active - Changed Plan" Phase

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#1909]
**Engagement URL:** https://cordfield.com/projects/5c4279049503d5cd78e84761
**Engagement ID:** 5c4279049503d5cd78e84761

Things checked:
- Has MOU dates
- Has funding partner 
- Has passed the "In Development" phase

Sensitive details: https://github.com/SeedCompany/management/issues/185

**Comment by ParkeBrown** [comment]
@parashara1 could you keep this on your priority list higher than other backlog bugs but lower than any PRs that need your help

Your review will help us determine how we can help the user

**Comment by parashara1** [comment]
@ParkeBrown definitely. I’m verifying Richard’s PRs as of now and will add this to my list above any other bugs in backlog! Will add comments here once I get around to reviewing!

**Comment by bryanjnelson** [comment]
Some additional data on this:

It appears as if, including this particular record, there are 9 instances of this scenario occurring in production.  All 9 of them occur on Internship Projects with the creation date of the Budget Node being the date of the v2 --> v3 migration.

**Comment by bryanjnelson** [comment]
Some additional data on this:

It appears as if, including this particular record, there are 9 instances of this scenario occurring in production. All 9 of them occur on Internship Projects with the creation date of the Budget Node being the date of the v2 --> v3 migration.

**Comment by bryanjnelson** [comment]
This issue seems to be occurring because the MOU dates were set manually during migration which caused the record sync handler to be skipped.  Currently in production the sync handler is also skipped during date changes because the projects are already active. This constraint was recently loosened in dev to allow for budget record changes to be applied with changesets.  After this change is released to Production we will alter one of the MOU dates (and alter it back) on each of these 9 projects which will fire off the sync handler and thus populate the budget with budget records.

This issue will be closed as there is no further development work to be completed at this time.
