### ISSUE TITLE
requestFileUpload > Getting "Error: connect ECONNREFUSED 127.0.0.1:80" error while user upload file

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#2001]
**Roles:** All 

**Describe the bug**
requestFileUpload > Getting `Error: connect ECONNREFUSED 127.0.0.1:80` error while user upload file

**Steps to Reproduce**
On Graphql playground or Postman - create an API request as below snap & attached notepad file and execute the request

**Expected Result**
File should be uploaded

**Actual Result**
Getting `Error: connect ECONNREFUSED 127.0.0.1:80` error while user upload file
See video -  

https://user-images.githubusercontent.com/5212585/124710399-58fc3700-df1a-11eb-9a9e-9ba3cf3208ab.mp4

**GraphQL Query:(requestFileUpload )**

![image](https://user-images.githubusercontent.com/5212585/124710513-85b04e80-df1a-11eb-8fcd-d550d185ebe7.png)

**Note:** Getting same error UI side also 
![image](https://user-images.githubusercontent.com/5212585/124711465-bd6bc600-df1b-11eb-93df-f7ec4659cfcd.png)

**GraphQL response**
```
Error: connect ECONNREFUSED 127.0.0.1:80
```

**Query and Input File**
[BugFileNotUploaded.txt](https://github.com/SeedCompany/cord-api-v3/files/6774877/BugFileNotUploaded.txt)

CordAPIV3# 136c06a1

**Comment by CarsonF** [comment]
This is because the API doesn't know it's running inside of a docker container. I added a "public port" config var so that docker can inform the API of this.

Fixed with 102d921ddff13a5ad8f6aa5fa6f91dcaa17f5bf8 and https://github.com/SeedCompany/cord-docs/wiki/Run-CORD-locally-with-Docker/_compare/306eb42e12710e1f8e84a56233f66015d8f92528

@iPiyushPatel @parashara1 You'll need to update your docker-compose.yml file from the WIKI.
