### ISSUE TITLE
"Failed to Connect to CORD Database" Error at Login

### ISSUE THREAD

**Issue by ParkeBrown** [SeedCompany/cord-api-v3#2157]
User gets the error when attempting to login

**Comment by ParkeBrown** [comment]
![Screen Shot 2021-09-17 at 9 40 02 AM](https://user-images.githubusercontent.com/5691814/133792638-17edbf0b-8533-4d1e-bfac-17065d01a256.png)

**Comment by ParkeBrown** [comment]
Appears users had issues starting arounnd Sep 16 6:30-6:40pm with responses not being returned but no error message

**Comment by sethmcknight** [comment]
Two questions to consider as a retro to this issue:

1) Why did users know about this but we didn't?
2) What do we need to do to find out about issues like this before users do?

**Comment by ParkeBrown** [comment]
Login started failing around Sep 17 930am ET
https://app.logrocket.com/x6d22y/cord-prod/sessions

**Comment by ParkeBrown** [comment]
Carson Full  5 minutes ago
ugh out of disk space

Carson Full  2 minutes ago
backups are not getting properly deleted. flushed for now.

**Comment by ParkeBrown** [comment]
Fix at Sep 17 9:58am ET or approx 30 min after login failure

**Comment by CarsonF** [comment]
## Problem
Ok it looks like full text indexes, reasonably, don't support booleans, lists, & temporal objects.
So when the one of these value types is added, the DB just skips adding these nodes to the index - at least that's what appears to be happening.
Since we've had the fulltext index (#2098) in prod for weeks and there haven't been any query problems this seems fine.

However, when running neo4j's consistency checker it seems to thinnk these nodes with non-string values should in fact be in the index & reports that there are inconsistencies.

The backup command automatically runs this & errors out when there are inconsistencies.
SInce the command errored out the cleanup part of the script never ran, leaving temporary backup folders.
Eventually these filled up the disk.

## Solution

I tried to drop the full text indexes and recreate them to fix the "inconsistency". This led to the same result.

Since everything operates fine and it's just this checker that has a problem I've disabled that step during backup runs.
Specifically, checking the indexes; other checks still run.

With that change backups are now flowing again.

The other change I made was the cleanup step now always runs regardless of backup errors, so we shouldn't run out of disk space again.

## Reporting

Obviously reporting on aspects of the DB would be helpful. I'd like to address this via another ticket. The other thing to consider is we are trying to get back to Aura, a hosted solution, which would relieve us of these concerns.
Once we remove all usages of SecurityGroups we can do this.
