### ISSUE TITLE
Create a `canAdmin` property to all permission.

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#453]
This isn't a refactor in the sense that it changes how current functions are used. This is adding a `admin` property to a `:Permission` node to show that (when true) a user can delegate permissions on that property. 

This ticket is to add the `admin` property on all generics. The default will be false, but the generic should take an optional parameter if it needs to be true. This will be used when someone is creating something. They will be the 'admin' of what they created by default. 

This work should not require the refactor of any caller. Those changes will be done afterwards.

**Comment by candleshine** [comment]
right now the admin property isn't used. that's why i want to update the generics first, which is all that ticket is asking. after that i want to use the admin property to determine if someone can assign another user with privileges. right now there is no way to know if a user can assign another user power


admins are permission carriers.  If you have the virus you can infect another user.  If you don’t you can’t

Michael Marshall  9:14 AM
right
New
9:15
so when you create a project, you'll be admin of that project and can create other admins and assign permissions to other users
9:16
but right now we are just updating the generics so all permissions have the property on them. next we'll update service functions so that when you create something, you have admin = true on all the properties
