### ISSUE TITLE
Get budget from a project query

### ISSUE THREAD

**Issue by candleshine** [SeedCompany/cord-api-v3#537]
Confirm Budget can be queried from Project

Verify that currentBudget query in the project.resolver works

**Comment by glassblowerscat** [comment]
@candleshine I've discovered that I actually mischaracterized this issue. I can query budget fields on a project—if I created that project. If it's a project I didn't create, I can't query any fields at all. Is this maybe intentional? It's kind of weird because I can query information for **all** projects with the `projects` query

**Comment by candleshine** [comment]
@glassblowerscat this is correct behavior. I think the project lists being open is a concession so that FE devs can get data before we get into API to give perms to other users.  

We can also open this one up, but that leads to holes that will need to be closed later.  Which we have a few already

@michaelmarshall agree?

**Comment by michaelmarshall** [comment]
sounds good

**Comment by ibohalsinghkoijam** [comment]
<img width="1308" alt="Budget from a project query" src="https://user-images.githubusercontent.com/24403111/85320751-30f18f80-b4e1-11ea-9e18-1fdc881f1c40.png">
