### ISSUE TITLE
Remove module exports from index files and reference modules directly in module files

### ISSUE THREAD

**Issue by michaelmarshall** [SeedCompany/cord-api-v3#607]
Remove all module exports in index files:
![image](https://user-images.githubusercontent.com/1165460/85783997-72ef2100-b6ed-11ea-9d08-40789b99cef1.png)

Change module references to use the module file:
![image](https://user-images.githubusercontent.com/1165460/85784133-93b77680-b6ed-11ea-81e8-d8dade8e86cc.png)

Then make sure all tests pass.

**Comment by CarsonF** [comment]
This is because those module classes are referenced directly (in `imports` array) when the file is loading (a side effect). Because these modules files contain side effects we want to isolate them from rest of the codebase.

This will not prevent circular dependency errors, but it will make resolution straight forward. We can see directly in the `imports` array what the module depends on in order to figure out where the `forwardRef`s are needed.

If services & DTOs were also loaded as apart of that module file/import statement they could also reference other dependencies that are not included in the module imports which is hard to track down.

**Comment by CarsonF** [comment]
Want to note here before I forget that this also applies to service dependencies. Since the constructor types are collected as the file is executing. This makes them no different from modules.
