### ISSUE TITLE
Project.deptId (departmentId) needs to be calculated and set when project status/step changes to 'Pending Finance Confirmation'

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#612]
Rename the property to `departmentId` while you're at it.

Department ID is a numeric ID that's auto incrementing. We treat it as a string here though because that's how we treat all IDs.
It doesn't just auto increment though because it has other logic it follows. Like year I think. We need to confirm with @sethmcknight @kjones140 or finance. We need to support this ID for new projects for finance until we can migrate them to our new IDs.

**Comment by candleshine** [comment]
This ticket is blocked until we have the scheme by which departmentId is coded; what is the algorithm for nextDepartmentId.

I imagine there's a cypher query for lastDeptId created. 
then a formula for the next one
then a way to move the pointer to the newly created One.  We need a lock for concurrent creates, hard to imagine in our app, but possible.

**Comment by sethmcknight** [comment]
Aaahhh Department ID's... where to begin.

Ok so a Department ID is a five digit number where the first digit corresponds to a specific Funding Account and the other four digits are a unique identifier within that Funding Account.

The Funding Account that a Project should be assigned to is based on the Location assigned to the Project. Each Location is assigned to one of 6 Funding Accounts. Each Funding Account has a unique number defined in the Funding Account data.

Within the Funding Account's range of Department ID's we would start with attempting to assign X0000 as the Project's Department ID. If X0000 is already assigned to a Project we iterate through until we find the first available Department ID within that Funding Account, in this example let's assume it is X0123.

If y'all want to we could then store X0124 as the next Department ID to try. However, because of the way these ID's used to be assigned, we are not guaranteed that X0124 - X9999 are unassigned. The next time that we need to assign a Department ID to a Project with the Funding Account of X, we will need to check if X0124 is available or if we need to try X0125, etc until we find the next number that has not been assigned.

Does that make sense @CarsonF & @candleshine?

The Financial Accounts should be in the database but here they are for your reference. Each Location has been linked to one of these in data (Incidentally @CarsonF we also need to surface the Location's Funding Account on the Language Page)

Asia - South (4)
Asia - Islands (3)
Pacific (7)
Africa (2)
Americas, Eurasia (5)
Asia - Mainland (1)

**Comment by CarsonF** [comment]
I'm glad I have you to remember all this stuff @sethmcknight ❤️ 

---

> However, because of the way these ID's used to be assigned, we are not guaranteed that X0124 - X9999 are unassigned.

Because they use to follow a date format right? And then we switched to auto incrementing?

---

> we also need to surface the Location's Funding Account on the Language Page

The language page or the location page? Or do you just mean showing the funding account in the location list?

---

How do these Funding Account compare to _Zones_? Why have both? I think I know the answer just looking for all the info I can get.


---

Department IDs for new projects are assigned when the project becomes Active? Otherwise the location can change or not be given yet.

---

Also what happens when the language changes after that point (like with a change of plan)? Does the department ID change with it if the funding account changes? That seems like a really small edge case. You probably don't have an answer for that, because it never happens. It's probably a small enough edge case that if/when it happens we can just change that data manually.

**Comment by candleshine** [comment]
If Funding Account is different from Zone, should the Funding Account be added to the schema? Last DeptId could be stored on either of those objects.

**Comment by sethmcknight** [comment]
@CarsonF see below
> > However, because of the way these ID's used to be assigned, we are not guaranteed that X0124 - X9999 are unassigned.
> Because they use to follow a date format right? And then we switched to auto incrementing?
Yes

> > we also need to surface the Location's Funding Account on the Language Page
> The language page or the location page? Or do you just mean showing the funding account in the location list?
Derp... I'm not really sure what I meant here. Thinking it through if the Language Engagement Card on a Language page includes the Department ID we'll be fine. Ignore this.

> How do these Funding Account compare to _Zones_? Why have both? I think I know the answer just looking for all the info I can get.
Funding Accounts have a specific set of Locations that they encompass. They have had the same set of Location since Seed Company began and Finance does not want to make adjustments to that on a regular basis. Zones are a way that our Field Operations group divides up Locations for ease of management. These and Regions have shifted and morphed over time and will continue to.
 
> Department IDs for new projects are assigned when the project becomes Active? Otherwise the location can change or not be given yet.
The Department ID should be assigned when a Project is submitted for Finance Confirmation. At that time Finance needs to have the Department ID available and a Location must be assigned.
 
> Also what happens when the language changes after that point (like with a change of plan)? Does the department ID change with it if the funding account changes? That seems like a really small edge case. You probably don't have an answer for that, because it never happens. It's probably a small enough edge case that if/when it happens we can just change that data manually.
No, the Department ID will not change due to accounting controls. If Languages are added or removed from a Project it won't matter as the Project holds the Department ID and we just create an Engagement or mark the Engagement as Terminated. In the rare case that a Project changes Location mid-way through the MOU, it will maintain the initial Department ID.

**Comment by zkhin** [comment]
I'm going to try to break this down into smaller tickets to help tackle this. @sethmcknight, will the new system have to query an old database for existing deptId entries? As in, are there already project deptId's that accounting uses and do they need to be seeded/migrated to the new system?

**Comment by sethmcknight** [comment]
@zkhin @CarsonF just saw that the title for this issue was misleading. 

The Department ID should be calculated and set when the project status/step is changed to 'Pending Finance Confirmation'. 

If the project already has a Department ID we do not need to recalculate or reassign a new Department ID, use the existing one.

**Comment by CarsonF** [comment]
> If the project already has a Department ID we do not need to recalculate or reassign a new Department ID, use the existing one.

Why or how would the project already have one?

**Comment by sethmcknight** [comment]
> > If the project already has a Department ID we do not need to recalculate or reassign a new Department ID, use the existing one.
> 
> Why or how would the project already have one?

@CarsonF Either because it was migrated or because it made it to the point of being assigned but then got pushed back in workflow (sent back for changes/corrections) and has now come back to the point where we would assign this.
