### ISSUE TITLE
Create Partner > Created Partner not shown on Partner list

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#613]
**Describe the bug**
Create Partner > Created Partner not shown on Partner list.

**Steps to Reproduce**
Refer Video :
https://www.awesomescreenshot.com/video/273477?key=74def6d257e6d1f8449bbc556f2a00c1

CoreField - 5d927722
CordAPIV3 - 4f3a71e

**Comment by punamasawa777** [comment]
This is Fixed with PR #650 
Removed agreementStatus From filters

<img width="1430" alt="Screenshot 2020-07-01 at 9 22 15 PM" src="https://user-images.githubusercontent.com/64840907/86272319-0348cc80-bbec-11ea-8d3d-ba2a2ed35d26.png">

<img width="1426" alt="Screenshot 2020-07-01 at 9 22 37 PM" src="https://user-images.githubusercontent.com/64840907/86272335-0774ea00-bbec-11ea-9a9c-1ddf4a809e3a.png">
