### ISSUE TITLE
Register > register($input: RegisterInput!) > User can register with empty password field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#682]
**Describe the bug**
Register > register($input: RegisterInput!) > User can register with empty password field.

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Validation message should be returned for 'password' field.

**Actual Result**
Registration is done successfully. See video - https://www.awesomescreenshot.com/video/346305?key=f868625654652e04b5899ebd87a2d658

GraphQL Query(register):
![image](https://user-images.githubusercontent.com/5212585/86777971-7385a100-c077-11ea-9b76-46dcca6b3d44.png)

**Query and Input File**
[register.txt](https://github.com/SeedCompany/cord-api-v3/files/4884673/register.txt)

CordAPIV3# 8b7caae

**Comment by punamasawa777** [comment]
This is Fixed with PR #697 

Here is The Fix with validations

<img width="1430" alt="Screenshot 2020-07-08 at 9 00 36 PM" src="https://user-images.githubusercontent.com/64840907/86952881-42899700-c171-11ea-8293-51d25856da20.png">


if validations passes

<img width="1432" alt="Screenshot 2020-07-08 at 9 00 56 PM" src="https://user-images.githubusercontent.com/64840907/86952911-503f1c80-c171-11ea-8611-0f901217756d.png">
