### ISSUE TITLE
Update User > updateUser($input: UpdateUserInput!) > User can update details with alphabetic characters in Phone field

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#684]
**Describe the bug**
Update User > updateUser($input: UpdateUserInput!) > User can update details with alphabetic characters in Phone field

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Validation message should be returned for 'phone ' field.

**Actual Result**
User details updated successfully. See video - https://www.awesomescreenshot.com/video/346451?key=f1f24df48be63a1b9353175cd9b1ac88

GraphQL Query( updateUser ):
![image](https://user-images.githubusercontent.com/5212585/86780668-9d8c9280-c07a-11ea-9ca1-0a8963321f51.png)

**Query and Input File**
[updateUser_phone_characters.txt](https://github.com/SeedCompany/cord-api-v3/files/4884764/updateUser_phone_characters.txt)

CordAPIV3# 8b7caae

┆Issue is synchronized with this [Monday item](https://seed-company-squad.monday.com/boards/3451697530/pulses/3466975432) by [Unito](https://www.unito.io)

**Comment by reneepe** [comment]
Bug verified.
![image.png](https://images.zenhubusercontent.com/5d66bac4a77bcf04870bc8bc/9a6d1a87-f19f-4fb2-9c09-6e091281c4dc)

**Comment by CarsonF** [comment]
We can't enforce this right now. We cannot assume that phone numbers are only US numbers. And we can't confirm that will migrated numbers will be valid according to this format.
We also don't want to enforce this yet because the frontend doesn't yet support this validation. We'll do more in the future to conform our data to a standard when it becomes a priority.
