### ISSUE TITLE
Get All Projects > query projects($input: ProjectListInput!) > Getting "Could not find user" error

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#693]
**Describe the bug**
Get All Projects > query projects($input: ProjectListInput!) > Getting "Could not find user" error.

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Project results are returned.

**Actual Result**
Project results are not returned. See video - https://www.awesomescreenshot.com/video/355555?key=3e81304c3e9934ed023dfc4b9b59a466

GraphQL Query ( projects ):
![image](https://user-images.githubusercontent.com/5212585/86927954-92586600-c151-11ea-936b-494c78371da2.png)

**Query and Input File**
[projects_userERROR.txt](https://github.com/SeedCompany/cord-api-v3/files/4891058/projects_userERROR.txt)

CordAPIV3# 3dd7156

**Comment by punamasawa777** [comment]
@iPiyushPatel ,  I have tried with latest master branch
--> It is working, here is result
This error is due to data inconsistency in DB
can you check from your end & let me know

<img width="1429" alt="Screenshot 2020-07-10 at 8 43 54 PM" src="https://user-images.githubusercontent.com/64840907/87171412-44c62f80-c2f0-11ea-805e-80ffa491e0ec.png">

<img width="1422" alt="Screenshot 2020-07-10 at 8 48 53 PM" src="https://user-images.githubusercontent.com/64840907/87171515-67f0df00-c2f0-11ea-9f32-88664ee159bb.png">

**Comment by iPiyushPatel** [comment]
Hi @punamasawa777 , I'm still getting the same issue. I already have latest master branch. See video - https://drive.google.com/file/d/1ZPNLG8Gu3oOC9JozGi9P5Fue-8Y_eNwv/view?usp=drivesdk

**Comment by iPiyushPatel** [comment]
I can't reproduce locally anymore, hence I'm closing. cc @CarsonF @michaelmarshall
