### ISSUE TITLE
Get All Projects > query projects($input: ProjectListInput!) > Getting "Could not find root directory associated to this project" error

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#703]
**Describe the bug**
Get All Projects > query projects($input: ProjectListInput!) > Getting "Could not find root directory associated to this project" error

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Project results are returned.

**Actual Result**
Getting "Could not find root directory associated to this project" error.
See video - https://www.awesomescreenshot.com/video/360751?key=91c5450332487f622750eb7d3dcd7f96

GraphQL Query ( projects ):
![image](https://user-images.githubusercontent.com/5212585/87000363-882a7c00-c1d2-11ea-8e4b-beef1aa4d322.png)

**Query and Input File**
[projects_rootDirectoryERROR.txt](https://github.com/SeedCompany/cord-api-v3/files/4894708/projects_rootDirectoryERROR.txt)

CordAPIV3# e5a7ad9

**Comment by zkhin** [comment]
@CarsonF This is related to this commit https://github.com/SeedCompany/cord-api-v3/commit/3b51dacde61d6593aa7bc601024c5664df4b3f17
Error occurs in `getRootDirectory` function because it tries to find `RootDirectory` before the `Project` is attached to `RootDirectory` in `AttachProjectRootDirectoryHandler`. Do you have any idea how to resolve this issue?

**Comment by CarsonF** [comment]
Yeah it looks like our override class isn't getting applied. I'll take a look.
