### ISSUE TITLE
Languages.projects

### ISSUE THREAD

**Issue by CarsonF** [SeedCompany/cord-api-v3#711]
Implement `LanguageService.listProjects`
https://github.com/SeedCompany/cord-api-v3/blob/3ae87dc3343a7e9d18a63cac7905ce06323692f9/src/components/language/language.service.ts#L531-L558

**Comment by candleshine** [comment]
List projects filter by language, does not belong in language service. It belongs in project service.

**Comment by candleshine** [comment]
We are having circular dependency errors because we cannot import project service into the language.resolver or the language.service.  Project module already depends on language.  I also think, conceptually, language should not know about Projects.  
@CarsonF is there a ResolveField way to call the projects list with filter on languageId here in the language resolver without needing to import project service?

**Comment by CarsonF** [comment]
@candleshine Have you tried using `forwardRef` like here?
https://github.com/SeedCompany/cord-api-v3/blob/eb0e88a3dc863893d01203a5914c42c811645588/src/components/project/project.service.ts#L78


----

If we don't want to directly couple these queries we have an option to do what we are doing with the event code but for queries.
```tsx
await this.queryBus.execute(new ProjectListQuery({ ...input, filter: { projectId } });
```
```tsx
@QueryHandler(ProjectListQuery)
export class ProjectListQueryHandler implements IQueryHandler<ProjectListQuery> {
  async execute(query: ProjectListQuery) {
    ...
  }
}
```

**Comment by ibohalsinghkoijam** [comment]
<img width="758" alt="ProjectList-Language" src="https://user-images.githubusercontent.com/24403111/88134966-91b8d880-cc03-11ea-9bf6-d67d4b8c84ee.png">
