### ISSUE TITLE
query languages > Sort by Name with 'ASC / DESC' order is not working

### ISSUE THREAD

**Issue by iPiyushPatel** [SeedCompany/cord-api-v3#816]
**Describe the bug**
query languages > Sort by Name with 'ASC / DESC' order is not working.

**Steps to Reproduce**
On Graphql playground or Postman - create a API request as below snap & attached notepad file and execute request.

**Expected Result**
Language items should be sorted by Name in ascending / descending order.

**Actual Result**
Sort by Name with 'ASC / DESC' order is not working.
See video - https://drive.google.com/file/d/1yKvCXe5oMS1cZCzjoZ1uFfaV9_QlS4QK/view?usp=drivesdk

GraphQL Query ( languages - DESC ):
![image](https://user-images.githubusercontent.com/5212585/88362574-9f549680-cd9a-11ea-8ba7-7a0bf6662720.png)

GraphQL Query ( languages - ASC ):
![image](https://user-images.githubusercontent.com/5212585/88362705-2ace2780-cd9b-11ea-8a7f-4332caff1d7b.png)

**Query and Input File**
[languages_sort.txt](https://github.com/SeedCompany/cord-api-v3/files/4970289/languages_sort.txt)

CordAPIV3# 5589755

**Comment by reneepe** [comment]
Bug verified. Languages where the first letter is uppercase are being sorted in alphabetical order and then the languages that begin with a lowercase letters are sorted alphabetically next. (ie, Tlanguage, Zlanguage, alanguage, dlanguage, ulanguage, etc.)

![image](https://user-images.githubusercontent.com/38309285/88388117-e08c7c80-cd81-11ea-8184-ccec188e1381.png)

**Comment by reneepe** [comment]
The problem is still persisting. The languages where the first letter is uppercase are being sorted in alphabetical order and then the languages that begin with a lowercase letters are sorted alphabetically next. They should be sorted by alphabetical order regardless of the case of the first letter.

Actual results: ie, Tlanguage, Zlanguage, alanguage, dlanguage, ulanguage, etc.

Expected results: ie, alanguage, dlanguage, Tlanguage, ulanguage, Zlanguage, etc.

![image](https://user-images.githubusercontent.com/38309285/88558271-4e8ea900-cff9-11ea-8c77-6eeff1b9ce6a.png)

**Comment by izquierdoalfredo** [comment]
@iPiyushPatel 
Now it works, Please check it again

**Comment by iPiyushPatel** [comment]
@izquierdoalfredo 
I can still replicate this issue
Please see the video :- https://drive.google.com/file/d/1f1OiXvuYUcvdWE7NeZN4JDY6I6yNCKbF/view?usp=sharing and let me know if any.

**Comment by izquierdoalfredo** [comment]
It's ASC order
![image](https://user-images.githubusercontent.com/68758109/92004176-e6299a80-ed0f-11ea-9908-5e482db91670.png)

It's DESC order
![image](https://user-images.githubusercontent.com/68758109/92004254-ff324b80-ed0f-11ea-9bf6-fb70fc101e07.png)

**Comment by iPiyushPatel** [comment]
Verified and passed.
